### ISSUE TITLE
bug: rectangles cannot be drawn touching or overlapping bottom edge of a window

### ISSUE THREAD

**Issue by aaaddd4747** [osgl-rbx/osgl#1]
doing so causes the following stack trace
```
 ReplicatedStorage.OSGL.DrawableObject.buffer:73: buffer access out of bounds  -  Client - buffer:73
  18:31:16.457  Stack Begin  -  Studio
  18:31:16.457  Script 'ReplicatedStorage.OSGL.DrawableObject.buffer', Line 73 - function WritePixel  -  Studio - buffer:73
  18:31:16.457  Script 'ReplicatedStorage.OSGL.DrawableObject', Line 101 - function WritePixel  -  Studio - DrawableObject:101
  18:31:16.457  Script 'ReplicatedStorage.OSGL.draw.writePixel', Line 5  -  Studio - writePixel:5
  18:31:16.457  Script 'ReplicatedStorage.OSGL.draw.fillPolygon', Line 34  -  Studio - fillPolygon:34
  18:31:16.458  Script 'ReplicatedStorage.OSGL.draw.rectangle', Line 82  -  Studio - rectangle:82
```

snippet from code i was toying with when i found this bug

```lua
local disp = script.Parent
local osgl = require(game.ReplicatedStorage.OSGL)
local win = osgl.Window.new(disp.SurfaceGui.Frame.ImageLabel,{sizeX=256,sizeY=256})
local function rectFromCentre(window,x,y,w,h,col,r)
	osgl.draw.rectangle(window,{height=h,width=w,xPos=x-w/2, yPos =y-h/2,fillColor=col,rotation=r})
end

while win:IsOpen() do
	osgl.draw.rectangle(win,{xPos=0,yPos=0,width=256,height=256,fillColor=color.BLACK})
	rectFromCentre(win,128,workspace.DistributedGameTime*10,16,16,color.BLUE,10)
	win:Render()
end
```
it is possible that this same sort of bug exists for other types of draw call but i havent tested any of those yet.
for now i can just wrap my draw calls in pcalls but i'd rather not have to do this

using this same code snippet, changing the rotation argument (set to 10 in the example) to 0 causes the rectangle draw to go completely haywire, not sure at all why it does that so i guess there's two bugs here

**Comment by saaawdust** [comment]
Hi,

Sorry for not responding sooner!
The issues you have described have been fixed! Drawing outside the window now works.
However, since `workspace.DistributedGameTime*10` may return a decimal-number, it's best to round it - Rotation will work however due to the intersection algorithm that is used.

You can download the latest version here: https://github.com/Gunshot-Sound-Studios/osgl-graphics/releases/tag/1.31b
